### ISSUE TITLE
Module build failed: TypeError: Property operator expected value to be one of ["void","throw","delete","!","+","-","~","typeof"] but got "++"

### ISSUE THREAD

**Issue by Akiyamka** [christensson/babel-plugin-transform-es2017-object-entries#2]
Babel 7 crush with that plugin.
Demonstration: https://github.com/Akiyamka/babel-playground

**Comment by rmartin** [comment]
@christensson - It appears that this fix was never deployed to NPM. Could you bump the version to 0.0.5 and deployed? It's till unresolved when testing VIA NPM install.

**Comment by christensson** [comment]
@rmartin Sorry for that. Published 0.0.5 to NPM.
